version: '3'

services:
  provider:
    image: dtr.rogfk.no/fint-beta/provider:1.3.6
    ports:
      - "8472:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /utdanning/utdanningsprogram/provider
      fint.events.orgIds: "fint.health,pwf.no"
      fint.events.component: pwf
      fint.events.env: pwf
      fint.audit.mongo.hostname: 152.93.213.138
      fint.audit.mongo.databasename: fint-audit-pwf
      fint.provider.sse-timeout-minutes: 19
      fint.hazelcast.members: consumer,provider
      endpoints.trace.sensitive: "false"
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  consumer:
    image: dtr.rogfk.no/fint-beta/consumer-utdanning-utdanningsprogram:0.0.1-2.6.0-rc-1
    ports:
      - "8473:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /utdanning/utdanningsprogram
      fint.consumer.default-org-id: "pwf.no"
      fint.consumer.override-org-id: "true"
      fint.events.orgIds: "fint.health,pwf.no"
      fint.events.component: pwf
      fint.events.env: pwf
      fint.relations.default-base-url: "https://play-with-fint.felleskomponent.no"
      fint.audit.mongo.hostname: 152.93.213.138
      fint.audit.mongo.databasename: fint-audit-pwf
      fint.hazelcast.members: consumer,provider
      fint.cache.manager: hazelcast
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  health-adapter:
    image: fint/health-adapter:latest
    environment:
      TZ: Europe/Oslo
      springfox.title: "Health Adapter"
      fint.adapter.organizations: fint.health
      fint.adapter.sse-endpoint: http://provider:8080/utdanning/utdanningsprogram/provider/sse/%s
      fint.adapter.status-endpoint: http://provider:8080/utdanning/utdanningsprogram/provider/status
      fint.adapter.response-endpoint: http://provider:8080/utdanning/utdanningsprogram/provider/response
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
